version: "3.9"

services:
  app:
    build: .
    container_name: tpa-2025-12-app-2
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ddstpa
      - DB_USER=postgres
      - DB_PASSWORD=1234abcd
      - PORT=9001
      - TIMEZONE=America/New_York
      - CORS_ALLOW_ANY_ORIGIN=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

  db:
    image: postgres:15
    container_name: tpa-2025-12-db-2
    environment:
      - POSTGRES_DB=ddstpa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234abcd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
